import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'tr' | 'es' | 'ko';

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'tr', label: 'Türkçe', flag: '🇹🇷' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'ko', label: '한국어', flag: '🇰🇷' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// UI translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    'landing.tagline': 'For Tattoo Artists',
    'landing.subtitle': 'Master art history from Renaissance to Contemporary — designed specifically for tattoo artists who want deeper roots in their craft.',
    'landing.feat1.title': '22 Art Movements',
    'landing.feat1.desc': 'Deep-dive lessons with tattoo-specific insights',
    'landing.feat2.title': 'Tattoo Tips & Techniques',
    'landing.feat2.desc': 'Each movement includes design guidance for ink',
    'landing.feat3.title': 'Weekly New Content',
    'landing.feat3.desc': 'A new movement unlocks every Sunday',
    'landing.cta.signup': 'Create Free Account',
    'landing.cta.signin': 'Sign In',
    'landing.powered': 'Powered by',
    'auth.welcome': 'Welcome back',
    'auth.create': 'Create your account',
    'auth.signin.sub': 'Sign in to continue your journey',
    'auth.signup.sub': 'Start your art history journey',
    'auth.name': 'Display Name',
    'auth.name.placeholder': 'Your name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signin': 'Sign In',
    'auth.signup': 'Create Account',
    'auth.no.account': "Don't have an account?",
    'auth.has.account': 'Already have an account?',
    'auth.switch.signup': 'Sign up',
    'auth.switch.signin': 'Sign in',
    'auth.error.name': 'Please enter your name.',
    'auth.error.password': 'Password must be at least 6 characters.',
    'back': '← Back',
    'nav.art_movements': 'Art Movements',
    'header.tagline': 'A Journey Through Art History',
    'header.total': 'Total',
    'header.live': 'Live',
    'header.soon': 'Soon',
    'timeline.explore': 'Explore Now →',
    'timeline.master': 'Master',
    'timeline.completed': 'Completed',
    'detail.back': 'Timeline',
    'detail.characteristics': 'Key Characteristics',
    'detail.artists': 'Notable Artists',
    'detail.tattoo_guide': "Tattoo Artist's Guide",
    'detail.design_tips': 'Design Tips',
    'detail.technical_tips': 'Technical Tips',
    'detail.inspiration': 'Modern Inspiration',
    'detail.origin.reaction': '⚡ Emerged as a reaction to',
    'detail.origin.evolution': '→ Evolved from',
    'detail.origin.parallel': '◎ Parallel to',
    'quiz.title': 'Knowledge Quiz',
    'quiz.question': 'Question',
    'quiz.of': 'of',
    'quiz.next': 'Next',
    'quiz.finish': 'Finish',
    'quiz.score': 'Your Score',
    'quiz.retake': 'Retake Quiz',
    'quiz.already': 'You already completed this quiz',
    'artworks.title': 'Notable Artworks',
    'leaderboard.title': 'Leaderboard',
    'translating': 'Translating...',
    'detail.listen': 'Listen',
    'detail.pause': 'Pause',
    'detail.resume': 'Resume',
    'detail.stop': 'Stop',
    'detail.loading': 'Loading…',
    'detail.continue': 'Continue',
    'detail.restart': 'From Start',
  },
  tr: {
    'landing.tagline': 'Dövme Sanatçıları İçin',
    'landing.subtitle': 'Rönesans\'tan Çağdaş sanata kadar sanat tarihinde ustalaşın — zanaatında daha derin kökler isteyen dövme sanatçıları için tasarlandı.',
    'landing.feat1.title': '22 Sanat Akımı',
    'landing.feat1.desc': 'Dövmeye özel içgörülerle derinlemesine dersler',
    'landing.feat2.title': 'Dövme İpuçları ve Teknikleri',
    'landing.feat2.desc': 'Her akım mürekkep için tasarım rehberi içerir',
    'landing.feat3.title': 'Haftalık Yeni İçerik',
    'landing.feat3.desc': 'Her Pazar yeni bir akım açılır',
    'landing.cta.signup': 'Ücretsiz Hesap Oluştur',
    'landing.cta.signin': 'Giriş Yap',
    'landing.powered': 'Altyapı',
    'auth.welcome': 'Tekrar hoş geldin',
    'auth.create': 'Hesabını oluştur',
    'auth.signin.sub': 'Yolculuğuna devam etmek için giriş yap',
    'auth.signup.sub': 'Sanat tarihi yolculuğuna başla',
    'auth.name': 'Görünen Ad',
    'auth.name.placeholder': 'Adın',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.signin': 'Giriş Yap',
    'auth.signup': 'Hesap Oluştur',
    'auth.no.account': 'Hesabın yok mu?',
    'auth.has.account': 'Zaten hesabın var mı?',
    'auth.switch.signup': 'Kayıt ol',
    'auth.switch.signin': 'Giriş yap',
    'auth.error.name': 'Lütfen adını gir.',
    'auth.error.password': 'Şifre en az 6 karakter olmalı.',
    'back': '← Geri',
    'nav.art_movements': 'Sanat Akımları',
    'header.tagline': 'Sanat Tarihi Yolculuğu',
    'header.total': 'Toplam',
    'header.live': 'Aktif',
    'header.soon': 'Yakında',
    'timeline.explore': 'Keşfet →',
    'timeline.master': 'Usta',
    'timeline.completed': 'Tamamlandı',
    'detail.back': 'Zaman Çizelgesi',
    'detail.characteristics': 'Temel Özellikler',
    'detail.artists': 'Öne Çıkan Sanatçılar',
    'detail.tattoo_guide': 'Dövme Sanatçısı Rehberi',
    'detail.design_tips': 'Tasarım İpuçları',
    'detail.technical_tips': 'Teknik İpuçları',
    'detail.inspiration': 'Modern İlham',
    'detail.origin.reaction': '⚡ Tepki olarak ortaya çıktı:',
    'detail.origin.evolution': '→ Evrildi:',
    'detail.origin.parallel': '◎ Paralel:',
    'quiz.title': 'Bilgi Quizi',
    'quiz.question': 'Soru',
    'quiz.of': '/',
    'quiz.next': 'Sonraki',
    'quiz.finish': 'Bitir',
    'quiz.score': 'Skorun',
    'quiz.retake': 'Tekrar Çöz',
    'quiz.already': 'Bu quizi zaten tamamladın',
    'artworks.title': 'Önemli Eserler',
    'leaderboard.title': 'Sıralama',
    'translating': 'Çevriliyor...',
    'detail.listen': 'Dinle',
    'detail.pause': 'Duraklat',
    'detail.resume': 'Devam',
    'detail.stop': 'Durdur',
    'detail.loading': 'Yükleniyor…',
    'detail.continue': 'Devam Et',
    'detail.restart': 'Baştan',
  },
  es: {
    'landing.tagline': 'Para Tatuadores',
    'landing.subtitle': 'Domina la historia del arte desde el Renacimiento hasta lo Contemporáneo — diseñado específicamente para tatuadores que quieren raíces más profundas en su oficio.',
    'landing.feat1.title': '22 Movimientos Artísticos',
    'landing.feat1.desc': 'Lecciones profundas con perspectivas para tatuadores',
    'landing.feat2.title': 'Consejos y Técnicas de Tatuaje',
    'landing.feat2.desc': 'Cada movimiento incluye guía de diseño para tinta',
    'landing.feat3.title': 'Contenido Nuevo Semanal',
    'landing.feat3.desc': 'Un nuevo movimiento se desbloquea cada domingo',
    'landing.cta.signup': 'Crear Cuenta Gratis',
    'landing.cta.signin': 'Iniciar Sesión',
    'landing.powered': 'Desarrollado por',
    'auth.welcome': 'Bienvenido de nuevo',
    'auth.create': 'Crea tu cuenta',
    'auth.signin.sub': 'Inicia sesión para continuar tu viaje',
    'auth.signup.sub': 'Comienza tu viaje por la historia del arte',
    'auth.name': 'Nombre',
    'auth.name.placeholder': 'Tu nombre',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.signin': 'Iniciar Sesión',
    'auth.signup': 'Crear Cuenta',
    'auth.no.account': '¿No tienes cuenta?',
    'auth.has.account': '¿Ya tienes cuenta?',
    'auth.switch.signup': 'Regístrate',
    'auth.switch.signin': 'Inicia sesión',
    'auth.error.name': 'Por favor ingresa tu nombre.',
    'auth.error.password': 'La contraseña debe tener al menos 6 caracteres.',
    'back': '← Atrás',
    'nav.art_movements': 'Movimientos Artísticos',
    'header.tagline': 'Un Viaje por la Historia del Arte',
    'header.total': 'Total',
    'header.live': 'Activos',
    'header.soon': 'Pronto',
    'timeline.explore': 'Explorar →',
    'timeline.master': 'Maestro',
    'timeline.completed': 'Completado',
    'detail.back': 'Línea de Tiempo',
    'detail.characteristics': 'Características Clave',
    'detail.artists': 'Artistas Notables',
    'detail.tattoo_guide': 'Guía para Tatuadores',
    'detail.design_tips': 'Consejos de Diseño',
    'detail.technical_tips': 'Consejos Técnicos',
    'detail.inspiration': 'Inspiración Moderna',
    'detail.origin.reaction': '⚡ Surgió como reacción a',
    'detail.origin.evolution': '→ Evolucionó de',
    'detail.origin.parallel': '◎ Paralelo a',
    'quiz.title': 'Quiz de Conocimiento',
    'quiz.question': 'Pregunta',
    'quiz.of': 'de',
    'quiz.next': 'Siguiente',
    'quiz.finish': 'Terminar',
    'quiz.score': 'Tu Puntuación',
    'quiz.retake': 'Repetir Quiz',
    'quiz.already': 'Ya completaste este quiz',
    'artworks.title': 'Obras Destacadas',
    'leaderboard.title': 'Clasificación',
    'translating': 'Traduciendo...',
    'detail.listen': 'Escuchar',
    'detail.pause': 'Pausar',
    'detail.resume': 'Continuar',
    'detail.stop': 'Detener',
    'detail.loading': 'Cargando…',
    'detail.continue': 'Continuar',
    'detail.restart': 'Desde el Inicio',
  },
  ko: {
    'landing.tagline': '타투 아티스트를 위한',
    'landing.subtitle': '르네상스부터 현대미술까지 — 자신의 예술에 더 깊은 뿌리를 원하는 타투 아티스트를 위해 설계되었습니다.',
    'landing.feat1.title': '22개 미술 사조',
    'landing.feat1.desc': '타투에 특화된 인사이트가 담긴 심층 수업',
    'landing.feat2.title': '타투 팁 & 기법',
    'landing.feat2.desc': '각 사조마다 잉크 디자인 가이드 포함',
    'landing.feat3.title': '매주 새로운 콘텐츠',
    'landing.feat3.desc': '매주 일요일 새로운 사조가 열립니다',
    'landing.cta.signup': '무료 계정 만들기',
    'landing.cta.signin': '로그인',
    'landing.powered': '제작',
    'auth.welcome': '다시 오신 것을 환영합니다',
    'auth.create': '계정 만들기',
    'auth.signin.sub': '여정을 계속하려면 로그인하세요',
    'auth.signup.sub': '미술사 여행을 시작하세요',
    'auth.name': '표시 이름',
    'auth.name.placeholder': '이름',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'auth.signin': '로그인',
    'auth.signup': '계정 만들기',
    'auth.no.account': '계정이 없으신가요?',
    'auth.has.account': '이미 계정이 있으신가요?',
    'auth.switch.signup': '회원가입',
    'auth.switch.signin': '로그인',
    'auth.error.name': '이름을 입력해 주세요.',
    'auth.error.password': '비밀번호는 최소 6자 이상이어야 합니다.',
    'back': '← 뒤로',
    'nav.art_movements': '미술 사조',
    'header.tagline': '미술사 여행',
    'header.total': '전체',
    'header.live': '공개',
    'header.soon': '곧',
    'timeline.explore': '탐험하기 →',
    'timeline.master': '마스터',
    'timeline.completed': '완료',
    'detail.back': '타임라인',
    'detail.characteristics': '주요 특징',
    'detail.artists': '주요 예술가',
    'detail.tattoo_guide': '타투 아티스트 가이드',
    'detail.design_tips': '디자인 팁',
    'detail.technical_tips': '기술 팁',
    'detail.inspiration': '현대적 영감',
    'detail.origin.reaction': '⚡ 반작용으로 탄생:',
    'detail.origin.evolution': '→ 발전:',
    'detail.origin.parallel': '◎ 병행:',
    'quiz.title': '지식 퀴즈',
    'quiz.question': '문제',
    'quiz.of': '/',
    'quiz.next': '다음',
    'quiz.finish': '완료',
    'quiz.score': '점수',
    'quiz.retake': '다시 풀기',
    'quiz.already': '이미 이 퀴즈를 완료했습니다',
    'artworks.title': '주요 작품',
    'leaderboard.title': '순위표',
    'translating': '번역 중...',
    'detail.listen': '듣기',
    'detail.pause': '일시정지',
    'detail.resume': '계속',
    'detail.stop': '정지',
    'detail.loading': '로딩 중…',
    'detail.continue': '이어서 듣기',
    'detail.restart': '처음부터',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};