import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { supabase } from '@/integrations/supabase/client';

export type Language = 'en' | 'tr' | 'es' | 'ko';

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'tr', label: 'Türkçe', flag: '🇹🇷' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'ko', label: '한국어', flag: '🇰🇷' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// UI translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    'landing.tagline': 'For Tattoo Artists',
    'landing.subtitle': 'Master art history from Renaissance to Contemporary — designed specifically for tattoo artists who want deeper roots in their craft.',
    'landing.feat1.title': '22 Art Movements',
    'landing.feat1.desc': 'Deep-dive lessons with tattoo-specific insights',
    'landing.feat2.title': 'Tattoo Tips & Techniques',
    'landing.feat2.desc': 'Each movement includes design guidance for ink',
    'landing.feat3.title': 'Weekly New Content',
    'landing.feat3.desc': 'A new movement unlocks every Sunday',
    'landing.cta.signup': 'Create Free Account',
    'landing.cta.signin': 'Sign In',
    'landing.powered': 'Powered by',
    'auth.welcome': 'Welcome back',
    'auth.create': 'Create your account',
    'auth.signin.sub': 'Sign in to continue your journey',
    'auth.signup.sub': 'Start your art history journey',
    'auth.name': 'Display Name',
    'auth.name.placeholder': 'Your name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signin': 'Sign In',
    'auth.signup': 'Create Account',
    'auth.no.account': "Don't have an account?",
    'auth.has.account': 'Already have an account?',
    'auth.switch.signup': 'Sign up',
    'auth.switch.signin': 'Sign in',
    'auth.error.name': 'Please enter your name.',
    'auth.error.password': 'Password must be at least 6 characters.',
    'back': '← Back',
    'nav.art_movements': 'Art Movements',
    'header.tagline': 'A Journey Through Art History',
    'header.total': 'Total',
    'header.live': 'Live',
    'header.soon': 'Soon',
    'timeline.explore': 'Explore Now →',
    'timeline.master': 'Master',
    'timeline.completed': 'Completed',
    'detail.back': 'Timeline',
    'detail.characteristics': 'Key Characteristics',
    'detail.artists': 'Notable Artists',
    'detail.tattoo_guide': "Tattoo Artist's Guide",
    'detail.design_tips': 'Design Tips',
    'detail.technical_tips': 'Technical Tips',
    'detail.inspiration': 'Modern Inspiration',
    'detail.origin.reaction': '⚡ Emerged as a reaction to',
    'detail.origin.evolution': '→ Evolved from',
    'detail.origin.parallel': '◎ Parallel to',
    'quiz.title': 'Knowledge Quiz',
    'quiz.question': 'Question',
    'quiz.of': 'of',
    'quiz.next': 'Next',
    'quiz.finish': 'Finish',
    'quiz.score': 'Your Score',
    'quiz.retake': 'Retake Quiz',
    'quiz.already': 'You already completed this quiz',
    'artworks.title': 'Notable Artworks',
    'leaderboard.title': 'Leaderboard',
    'translating': 'Translating...',
    'detail.listen': 'Listen',
    'detail.pause': 'Pause',
    'detail.resume': 'Resume',
    'detail.stop': 'Stop',
    'detail.loading': 'Loading…',
    'detail.continue': 'Continue',
    'detail.restart': 'From Start',
    'updates.title': "What's New",
    'updates.empty': 'No updates yet. Stay tuned!',
    'tour.prev': 'Back',
    'tour.next': 'Next',
    'tour.finish': "Let's go!",
    'tour.home.timeline.title': 'Explore Art Movements',
    'tour.home.timeline.content': 'Tap any movement to discover detailed info, artworks, artists, and quizzes.',
    'tour.home.language.title': 'Language Selection',
    'tour.home.language.content': 'Read content in different languages — English, Turkish, Korean, Spanish.',
    'tour.home.theme.title': 'Switch Theme',
    'tour.home.theme.content': 'Toggle between gold and dark themes to personalize your reading experience.',
    'tour.home.updates.title': 'Updates',
    'tour.home.updates.content': 'Get notified about newly added movements and features.',
    'tour.home.leaderboard.title': 'Leaderboard',
    'tour.home.leaderboard.content': 'Compare your quiz scores with other users and aim for the top!',
    'tour.detail.summary.title': 'Movement Overview',
    'tour.detail.summary.content': 'Detailed description of the movement\'s history, origins, and philosophy. Use the audio feature to listen along.',
    'tour.detail.characteristics.title': 'Key Characteristics',
    'tour.detail.characteristics.content': 'Artistic characteristics that define the movement — color usage, composition, techniques, and philosophical approaches.',
    'tour.detail.artists.title': 'Notable Artists',
    'tour.detail.artists.content': 'The pioneering and most influential artists of the movement, their life years and artistic contributions.',
    'tour.detail.tattoo.title': 'Tattoo Guide',
    'tour.detail.tattoo.content': 'Tattoo design tips inspired by this movement — technical advice, design ideas, and sources of inspiration.',
    'tour.detail.quiz.title': 'Knowledge Quiz',
    'tour.detail.quiz.content': 'Test what you\'ve learned with a 10-question quiz at the end of each movement. Your scores are reflected on the leaderboard!',
    'auth.language': 'Preferred Language',
    'profile.title': 'Profile',
    'profile.bio': 'Bio',
    'profile.bio.placeholder': 'Tell us about yourself and your art...',
    'profile.instagram': 'Instagram',
    'profile.instagram.placeholder': '@yourusername',
    'profile.website': 'Website',
    'profile.website.placeholder': 'https://yourwebsite.com',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.saved': 'Profile saved!',
    'profile.stats': 'Quiz Stats',
    'profile.quizzes_completed': 'Quizzes Completed',
    'profile.avg_score': 'Average Score',
    'comments.title': 'Comments',
    'comments.placeholder': 'Share your thoughts on this movement...',
    'comments.submit': 'Post',
    'comments.empty': 'No comments yet. Be the first!',
    'comments.delete': 'Delete',
  },
  tr: {
    'landing.tagline': 'Dövme Sanatçıları İçin',
    'landing.subtitle': 'Rönesans\'tan Çağdaş sanata kadar sanat tarihinde ustalaşın — zanaatında daha derin kökler isteyen dövme sanatçıları için tasarlandı.',
    'landing.feat1.title': '22 Sanat Akımı',
    'landing.feat1.desc': 'Dövmeye özel içgörülerle derinlemesine dersler',
    'landing.feat2.title': 'Dövme İpuçları ve Teknikleri',
    'landing.feat2.desc': 'Her akım mürekkep için tasarım rehberi içerir',
    'landing.feat3.title': 'Haftalık Yeni İçerik',
    'landing.feat3.desc': 'Her Pazar yeni bir akım açılır',
    'landing.cta.signup': 'Ücretsiz Hesap Oluştur',
    'landing.cta.signin': 'Giriş Yap',
    'landing.powered': 'Altyapı',
    'auth.welcome': 'Tekrar hoş geldin',
    'auth.create': 'Hesabını oluştur',
    'auth.signin.sub': 'Yolculuğuna devam etmek için giriş yap',
    'auth.signup.sub': 'Sanat tarihi yolculuğuna başla',
    'auth.name': 'Görünen Ad',
    'auth.name.placeholder': 'Adın',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.signin': 'Giriş Yap',
    'auth.signup': 'Hesap Oluştur',
    'auth.no.account': 'Hesabın yok mu?',
    'auth.has.account': 'Zaten hesabın var mı?',
    'auth.switch.signup': 'Kayıt ol',
    'auth.switch.signin': 'Giriş yap',
    'auth.error.name': 'Lütfen adını gir.',
    'auth.error.password': 'Şifre en az 6 karakter olmalı.',
    'back': '← Geri',
    'nav.art_movements': 'Sanat Akımları',
    'header.tagline': 'Sanat Tarihi Yolculuğu',
    'header.total': 'Toplam',
    'header.live': 'Aktif',
    'header.soon': 'Yakında',
    'timeline.explore': 'Keşfet →',
    'timeline.master': 'Usta',
    'timeline.completed': 'Tamamlandı',
    'detail.back': 'Zaman Çizelgesi',
    'detail.characteristics': 'Temel Özellikler',
    'detail.artists': 'Öne Çıkan Sanatçılar',
    'detail.tattoo_guide': 'Dövme Sanatçısı Rehberi',
    'detail.design_tips': 'Tasarım İpuçları',
    'detail.technical_tips': 'Teknik İpuçları',
    'detail.inspiration': 'Modern İlham',
    'detail.origin.reaction': '⚡ Tepki olarak ortaya çıktı:',
    'detail.origin.evolution': '→ Evrildi:',
    'detail.origin.parallel': '◎ Paralel:',
    'quiz.title': 'Bilgi Quizi',
    'quiz.question': 'Soru',
    'quiz.of': '/',
    'quiz.next': 'Sonraki',
    'quiz.finish': 'Bitir',
    'quiz.score': 'Skorun',
    'quiz.retake': 'Tekrar Çöz',
    'quiz.already': 'Bu quizi zaten tamamladın',
    'artworks.title': 'Önemli Eserler',
    'leaderboard.title': 'Sıralama',
    'translating': 'Çevriliyor...',
    'detail.listen': 'Dinle',
    'detail.pause': 'Duraklat',
    'detail.resume': 'Devam',
    'detail.stop': 'Durdur',
    'detail.loading': 'Yükleniyor…',
    'detail.continue': 'Devam Et',
    'detail.restart': 'Baştan',
    'updates.title': 'Yenilikler',
    'updates.empty': 'Henüz güncelleme yok. Takipte kalın!',
    'tour.prev': 'Geri',
    'tour.next': 'İleri',
    'tour.finish': 'Başla!',
    'tour.home.timeline.title': 'Sanat Akımlarını Keşfet',
    'tour.home.timeline.content': 'Her akıma tıklayarak detaylı bilgi, eserler, sanatçılar ve quizlere ulaşabilirsin.',
    'tour.home.language.title': 'Dil Seçimi',
    'tour.home.language.content': 'İçerikleri farklı dillerde okuyabilirsin — Türkçe, İngilizce, Korece, İspanyolca.',
    'tour.home.theme.title': 'Tema Değiştir',
    'tour.home.theme.content': 'Altın ve koyu tema arasında geçiş yaparak okuma deneyimini kişiselleştir.',
    'tour.home.updates.title': 'Güncellemeler',
    'tour.home.updates.content': 'Yeni eklenen akımlar ve özellikler hakkında bildirim al.',
    'tour.home.leaderboard.title': 'Sıralama Tablosu',
    'tour.home.leaderboard.content': 'Quiz puanlarını diğer kullanıcılarla karşılaştır ve en iyi ol!',
    'tour.detail.summary.title': 'Akım Özeti',
    'tour.detail.summary.content': 'Akımın tarihçesi, kökeni ve genel felsefesi hakkında detaylı açıklama. Sesli dinleme özelliğiyle metni kulaklıktan takip edebilirsin.',
    'tour.detail.characteristics.title': 'Temel Özellikler',
    'tour.detail.characteristics.content': 'Akımı tanımlayan sanatsal özellikler — renk kullanımı, kompozisyon, teknik ve felsefi yaklaşımlar.',
    'tour.detail.artists.title': 'Önemli Sanatçılar',
    'tour.detail.artists.content': 'Akımın öncü ve en etkili sanatçıları, yaşam yılları ve sanatsal katkıları.',
    'tour.detail.tattoo.title': 'Dövme Rehberi',
    'tour.detail.tattoo.content': 'Bu akımdan ilham alan dövme tasarım ipuçları — teknik öneriler, tasarım fikirleri ve ilham kaynakları.',
    'tour.detail.quiz.title': 'Bilgi Testi',
    'tour.detail.quiz.content': 'Her akımın sonunda 10 soruluk quiz ile öğrendiklerini test et. Puanların sıralama tablosuna yansır!',
    'auth.language': 'Tercih Edilen Dil',
    'profile.title': 'Profil',
    'profile.bio': 'Hakkında',
    'profile.bio.placeholder': 'Kendin ve sanatın hakkında birşeyler yaz...',
    'profile.instagram': 'Instagram',
    'profile.instagram.placeholder': '@kullaniciadin',
    'profile.website': 'Web Sitesi',
    'profile.website.placeholder': 'https://sitendomain.com',
    'profile.save': 'Değişiklikleri Kaydet',
    'profile.saving': 'Kaydediliyor...',
    'profile.saved': 'Profil kaydedildi!',
    'profile.stats': 'Quiz İstatistikleri',
    'profile.quizzes_completed': 'Tamamlanan Quiz',
    'profile.avg_score': 'Ortalama Puan',
  },
  es: {
    'landing.tagline': 'Para Tatuadores',
    'landing.subtitle': 'Domina la historia del arte desde el Renacimiento hasta lo Contemporáneo — diseñado específicamente para tatuadores que quieren raíces más profundas en su oficio.',
    'landing.feat1.title': '22 Movimientos Artísticos',
    'landing.feat1.desc': 'Lecciones profundas con perspectivas para tatuadores',
    'landing.feat2.title': 'Consejos y Técnicas de Tatuaje',
    'landing.feat2.desc': 'Cada movimiento incluye guía de diseño para tinta',
    'landing.feat3.title': 'Contenido Nuevo Semanal',
    'landing.feat3.desc': 'Un nuevo movimiento se desbloquea cada domingo',
    'landing.cta.signup': 'Crear Cuenta Gratis',
    'landing.cta.signin': 'Iniciar Sesión',
    'landing.powered': 'Desarrollado por',
    'auth.welcome': 'Bienvenido de nuevo',
    'auth.create': 'Crea tu cuenta',
    'auth.signin.sub': 'Inicia sesión para continuar tu viaje',
    'auth.signup.sub': 'Comienza tu viaje por la historia del arte',
    'auth.name': 'Nombre',
    'auth.name.placeholder': 'Tu nombre',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.signin': 'Iniciar Sesión',
    'auth.signup': 'Crear Cuenta',
    'auth.no.account': '¿No tienes cuenta?',
    'auth.has.account': '¿Ya tienes cuenta?',
    'auth.switch.signup': 'Regístrate',
    'auth.switch.signin': 'Inicia sesión',
    'auth.error.name': 'Por favor ingresa tu nombre.',
    'auth.error.password': 'La contraseña debe tener al menos 6 caracteres.',
    'back': '← Atrás',
    'nav.art_movements': 'Movimientos Artísticos',
    'header.tagline': 'Un Viaje por la Historia del Arte',
    'header.total': 'Total',
    'header.live': 'Activos',
    'header.soon': 'Pronto',
    'timeline.explore': 'Explorar →',
    'timeline.master': 'Maestro',
    'timeline.completed': 'Completado',
    'detail.back': 'Línea de Tiempo',
    'detail.characteristics': 'Características Clave',
    'detail.artists': 'Artistas Notables',
    'detail.tattoo_guide': 'Guía para Tatuadores',
    'detail.design_tips': 'Consejos de Diseño',
    'detail.technical_tips': 'Consejos Técnicos',
    'detail.inspiration': 'Inspiración Moderna',
    'detail.origin.reaction': '⚡ Surgió como reacción a',
    'detail.origin.evolution': '→ Evolucionó de',
    'detail.origin.parallel': '◎ Paralelo a',
    'quiz.title': 'Quiz de Conocimiento',
    'quiz.question': 'Pregunta',
    'quiz.of': 'de',
    'quiz.next': 'Siguiente',
    'quiz.finish': 'Terminar',
    'quiz.score': 'Tu Puntuación',
    'quiz.retake': 'Repetir Quiz',
    'quiz.already': 'Ya completaste este quiz',
    'artworks.title': 'Obras Destacadas',
    'leaderboard.title': 'Clasificación',
    'translating': 'Traduciendo...',
    'detail.listen': 'Escuchar',
    'detail.pause': 'Pausar',
    'detail.resume': 'Continuar',
    'detail.stop': 'Detener',
    'detail.loading': 'Cargando…',
    'detail.continue': 'Continuar',
    'detail.restart': 'Desde el Inicio',
    'updates.title': 'Novedades',
    'updates.empty': 'Sin actualizaciones aún. ¡Mantente atento!',
    'tour.prev': 'Atrás',
    'tour.next': 'Siguiente',
    'tour.finish': '¡Vamos!',
    'tour.home.timeline.title': 'Explora los Movimientos',
    'tour.home.timeline.content': 'Toca cualquier movimiento para descubrir información detallada, obras, artistas y cuestionarios.',
    'tour.home.language.title': 'Selección de Idioma',
    'tour.home.language.content': 'Lee el contenido en diferentes idiomas — inglés, turco, coreano, español.',
    'tour.home.theme.title': 'Cambiar Tema',
    'tour.home.theme.content': 'Alterna entre temas dorado y oscuro para personalizar tu experiencia de lectura.',
    'tour.home.updates.title': 'Actualizaciones',
    'tour.home.updates.content': 'Recibe notificaciones sobre nuevos movimientos y funciones añadidas.',
    'tour.home.leaderboard.title': 'Clasificación',
    'tour.home.leaderboard.content': '¡Compara tus puntuaciones con otros usuarios y llega a la cima!',
    'tour.detail.summary.title': 'Resumen del Movimiento',
    'tour.detail.summary.content': 'Descripción detallada de la historia, orígenes y filosofía del movimiento. Usa la función de audio para escuchar.',
    'tour.detail.characteristics.title': 'Características Clave',
    'tour.detail.characteristics.content': 'Características artísticas que definen el movimiento — uso del color, composición, técnicas y enfoques filosóficos.',
    'tour.detail.artists.title': 'Artistas Notables',
    'tour.detail.artists.content': 'Los artistas pioneros y más influyentes del movimiento, sus años de vida y contribuciones artísticas.',
    'tour.detail.tattoo.title': 'Guía de Tatuaje',
    'tour.detail.tattoo.content': 'Consejos de diseño de tatuajes inspirados en este movimiento — consejos técnicos, ideas de diseño y fuentes de inspiración.',
    'tour.detail.quiz.title': 'Quiz de Conocimiento',
    'tour.detail.quiz.content': '¡Pon a prueba lo aprendido con un quiz de 10 preguntas al final de cada movimiento. Tus puntuaciones se reflejan en la clasificación!',
    'auth.language': 'Idioma Preferido',
    'profile.title': 'Perfil',
    'profile.bio': 'Biografía',
    'profile.bio.placeholder': 'Cuéntanos sobre ti y tu arte...',
    'profile.instagram': 'Instagram',
    'profile.instagram.placeholder': '@tuusuario',
    'profile.website': 'Sitio Web',
    'profile.website.placeholder': 'https://tusitio.com',
    'profile.save': 'Guardar Cambios',
    'profile.saving': 'Guardando...',
    'profile.saved': '¡Perfil guardado!',
    'profile.stats': 'Estadísticas de Quiz',
    'profile.quizzes_completed': 'Quizzes Completados',
    'profile.avg_score': 'Puntuación Media',
  },
  ko: {
    'landing.tagline': '타투 아티스트를 위한',
    'landing.subtitle': '르네상스부터 현대미술까지 — 자신의 예술에 더 깊은 뿌리를 원하는 타투 아티스트를 위해 설계되었습니다.',
    'landing.feat1.title': '22개 미술 사조',
    'landing.feat1.desc': '타투에 특화된 인사이트가 담긴 심층 수업',
    'landing.feat2.title': '타투 팁 & 기법',
    'landing.feat2.desc': '각 사조마다 잉크 디자인 가이드 포함',
    'landing.feat3.title': '매주 새로운 콘텐츠',
    'landing.feat3.desc': '매주 일요일 새로운 사조가 열립니다',
    'landing.cta.signup': '무료 계정 만들기',
    'landing.cta.signin': '로그인',
    'landing.powered': '제작',
    'auth.welcome': '다시 오신 것을 환영합니다',
    'auth.create': '계정 만들기',
    'auth.signin.sub': '여정을 계속하려면 로그인하세요',
    'auth.signup.sub': '미술사 여행을 시작하세요',
    'auth.name': '표시 이름',
    'auth.name.placeholder': '이름',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'auth.signin': '로그인',
    'auth.signup': '계정 만들기',
    'auth.no.account': '계정이 없으신가요?',
    'auth.has.account': '이미 계정이 있으신가요?',
    'auth.switch.signup': '회원가입',
    'auth.switch.signin': '로그인',
    'auth.error.name': '이름을 입력해 주세요.',
    'auth.error.password': '비밀번호는 최소 6자 이상이어야 합니다.',
    'back': '← 뒤로',
    'nav.art_movements': '미술 사조',
    'header.tagline': '미술사 여행',
    'header.total': '전체',
    'header.live': '공개',
    'header.soon': '곧',
    'timeline.explore': '탐험하기 →',
    'timeline.master': '마스터',
    'timeline.completed': '완료',
    'detail.back': '타임라인',
    'detail.characteristics': '주요 특징',
    'detail.artists': '주요 예술가',
    'detail.tattoo_guide': '타투 아티스트 가이드',
    'detail.design_tips': '디자인 팁',
    'detail.technical_tips': '기술 팁',
    'detail.inspiration': '현대적 영감',
    'detail.origin.reaction': '⚡ 반작용으로 탄생:',
    'detail.origin.evolution': '→ 발전:',
    'detail.origin.parallel': '◎ 병행:',
    'quiz.title': '지식 퀴즈',
    'quiz.question': '문제',
    'quiz.of': '/',
    'quiz.next': '다음',
    'quiz.finish': '완료',
    'quiz.score': '점수',
    'quiz.retake': '다시 풀기',
    'quiz.already': '이미 이 퀴즈를 완료했습니다',
    'artworks.title': '주요 작품',
    'leaderboard.title': '순위표',
    'translating': '번역 중...',
    'detail.listen': '듣기',
    'detail.pause': '일시정지',
    'detail.resume': '계속',
    'detail.stop': '정지',
    'detail.loading': '로딩 중…',
    'detail.continue': '이어서 듣기',
    'detail.restart': '처음부터',
    'updates.title': '새로운 소식',
    'updates.empty': '아직 업데이트가 없습니다. 기대해주세요!',
    'tour.prev': '이전',
    'tour.next': '다음',
    'tour.finish': '시작하기!',
    'tour.home.timeline.title': '미술 사조 탐험',
    'tour.home.timeline.content': '각 사조를 탭하여 상세 정보, 작품, 예술가, 퀴즈를 확인하세요.',
    'tour.home.language.title': '언어 선택',
    'tour.home.language.content': '영어, 터키어, 한국어, 스페인어 등 다양한 언어로 콘텐츠를 읽을 수 있습니다.',
    'tour.home.theme.title': '테마 변경',
    'tour.home.theme.content': '골드와 다크 테마 사이를 전환하여 읽기 경험을 맞춤 설정하세요.',
    'tour.home.updates.title': '업데이트',
    'tour.home.updates.content': '새로 추가된 사조와 기능에 대한 알림을 받으세요.',
    'tour.home.leaderboard.title': '순위표',
    'tour.home.leaderboard.content': '다른 사용자들과 퀴즈 점수를 비교하고 1위를 노리세요!',
    'tour.detail.summary.title': '사조 개요',
    'tour.detail.summary.content': '사조의 역사, 기원, 철학에 대한 상세한 설명입니다. 오디오 기능으로 들으며 따라갈 수 있습니다.',
    'tour.detail.characteristics.title': '주요 특징',
    'tour.detail.characteristics.content': '사조를 정의하는 예술적 특성 — 색상 사용, 구성, 기법, 철학적 접근.',
    'tour.detail.artists.title': '주요 예술가',
    'tour.detail.artists.content': '사조의 선구적이고 가장 영향력 있는 예술가들, 생몰년과 예술적 기여.',
    'tour.detail.tattoo.title': '타투 가이드',
    'tour.detail.tattoo.content': '이 사조에서 영감을 받은 타투 디자인 팁 — 기술적 조언, 디자인 아이디어, 영감의 원천.',
    'tour.detail.quiz.title': '지식 퀴즈',
    'tour.detail.quiz.content': '각 사조 끝에 10문제 퀴즈로 배운 것을 테스트하세요. 점수는 순위표에 반영됩니다!',
    'auth.language': '선호 언어',
    'profile.title': '프로필',
    'profile.bio': '소개',
    'profile.bio.placeholder': '자신과 예술에 대해 알려주세요...',
    'profile.instagram': 'Instagram',
    'profile.instagram.placeholder': '@사용자이름',
    'profile.website': '웹사이트',
    'profile.website.placeholder': 'https://yourwebsite.com',
    'profile.save': '변경 저장',
    'profile.saving': '저장 중...',
    'profile.saved': '프로필이 저장되었습니다!',
    'profile.stats': '퀴즈 통계',
    'profile.quizzes_completed': '완료한 퀴즈',
    'profile.avg_score': '평균 점수',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  // Sync language to DB on mount for email preferences
  useEffect(() => {
    const syncLang = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        await supabase
          .from('notification_preferences')
          .upsert({ user_id: user.id, language, email_notifications: true }, { onConflict: 'user_id' });
      }
    };
    syncLang();
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
    // Sync to DB for email language preference
    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      await supabase
        .from('notification_preferences')
        .upsert({ user_id: user.id, language: lang, email_notifications: true }, { onConflict: 'user_id' });
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};